on: [push]
name: Deploy Ghost to Azure
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./deploy/ghost.bicep
        parameters: databasePassword=${{ secrets.GHOST_MYSQL_PASSWORD }}
        failOnStdErr: false
        
  load-test:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Azure Load Testing
      - uses: azure/load-testing@v1
        with:
          loadTestConfigFile: config.yaml
          loadTestResource: 'ltdemo'
          resourceGroup: ${{ secrets.AZURE_RG }}        

